---
- name: "create group {{ manage_user_group }}"
  group:
    name: "{{ manage_user_group }}"

- name: "users exist {{ manage_user_name }}  {{ manage_user_group }}"
  user:
    name: "{{ manage_user_name }}"
    state: present
    password: "{{ manage_user_password }}"
    group: "{{ manage_user_group }}"
    shell: /bin/bash

- name: "directory create /home/{{ manage_user_name }}/.ssh"
  file:
    path: "/home/{{ manage_user_name }}/.ssh"
    state: directory
    owner: "{{ manage_user_name }}"
    group: "{{ manage_user_group }}"
    mode: 0700

# add key
- name: authorized_keys
  copy:
    src: "home/manage_user/.ssh/authorized_keys"
    dest: "/home/{{ manage_user_name }}/.ssh/authorized_keys"
    owner: "{{ manage_user_name }}"
    group: "{{ manage_user_group }}"
    mode: 0600

- name: set profile
  copy:
    src: "home/manage_user/.profile"
    dest: "/home/{{ manage_user_name }}/.profile"
    owner: "{{ manage_user_name }}"
    group: "{{ manage_user_group }}"
    mode: 0644

- name: set bashrc
  copy:
    src: "home/manage_user/.bashrc"
    dest: "/home/{{ manage_user_name }}/.bashrc"
    owner: "{{ manage_user_name }}"
    group: "{{ manage_user_group }}"
    mode: 0644

- name: add kernel parameters and reload
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/common.conf
  with_items:
    - name: vm.max_map_count
      value: 262144
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.core.somaxconn
      value: 65535
    - name: net.ipv4.tcp_max_syn_backlog
      value: 65535
    - name: net.core.netdev_max_backlog
      value: 16384
    - name: net.ipv4.conf.all.forwarding
      value: 1

- name: "change hostname to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: Generate /etc/hosts file
  template:
    src: "etc/hosts"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

- name: "create group {{ ansible_user_group }}"
  group:
    name: "{{ ansible_user_group }}"

- name: "users exist name:{{ ansible_user_name }} group:{{ ansible_user_group }}"
  user:
    name: "{{ ansible_user_name }}"
    state: present
    password: "{{ ansible_user_password }}"
    group: "{{ ansible_user_group }}"

- name: "directory create /home/{{ ansible_user_name }}/.ssh"
  file:
    path: "/home/{{ ansible_user_name }}/.ssh"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0700

- name: "create /home/{{ ansible_user_name }}/.ssh/config"
  copy:
    src: "home/ansible/.ssh/config"
    dest: "/home/{{ ansible_user_name }}/.ssh/config"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0600

# add key
- name: authorized_keys
  copy:
    src: "home/ansible/.ssh/authorized_keys"
    dest: "/home/{{ ansible_user_name }}/.ssh/authorized_keys"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0600

- name: "create project root directory {{ project_root_dir }}"
  file:
    path: "{{ project_root_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "create project cert directory {{ project_cert_dir }}"
  file:
    path: "{{ project_cert_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "create project script directory {{ script_dir }}"
  file:
    path: "{{ script_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "create project config directory {{ config_dir }}"
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: include distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_version }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'

- name: "root user password change"
  user:
    name: "{{ root_user_name }}"
    password: "{{ root_user_password }}"
