---
- name: setenforce 0
  shell: "setenforce 0"
  register: salt
  ignore_errors: true
  changed_when: false

- name: Disable setting of SELinux
  selinux:
    state: disabled

- name: install common package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ansible
      - chrony
      - ibus-kkc
      - postfix
      - "vlgothic-*"

- name: "localedef"
  command: localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
  check_mode: no

- name: "set ja_JP to /etc/locale.conf"
  command: bash -c "echo 'LANG="ja_JP.UTF-8"' > /etc/locale.conf"
  check_mode: no

- name: "set ja_JP"
  command: bash -c "source /etc/locale.conf"
  check_mode: no

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# - name: Set timezone to Japan
#   file:
#     src: /usr/share/zoneinfo/Japan
#     path: /etc/localtime
#     state: link
#     force: yes

- name: set state chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
